### ISSUE TITLE
Include an external monitoring system using DataDog or Grafana

### ISSUE THREAD

**Issue by JoshC98** [GDoesCode/COM619DevOpsGroupWork#15]

**Comment by GDoesCode** [comment]
Prometheus: https://prometheus.io/

**Comment by jacob-shattock-solent** [comment]
Created an account with solar winds, it seems to be running fine, need to wait for some data to come in to further clarify.

**Comment by DAghaSolent** [comment]
What do you mean by data to come in to clarify?
