### ISSUE TITLE
The site will respect GPDR guidelines (Danny & Muhammad)

### ISSUE THREAD

**Issue by GDoesCode** [GDoesCode/COM619DevOpsGroupWork#24]

**Comment by DAghaSolent** [comment]
Currently writing out documentation regarding GDPR guidelines. Once completed will send to the group for review and feedback before deploying it onto the mapping application.

**Comment by DAghaSolent** [comment]
Completed a draft just sending it to the team for review to see if it's all good then we will publish it onto the application.
