### ISSUE TITLE
Setting up Docker and running map JS application in Azure

### ISSUE THREAD

**Issue by DAghaSolent** [GDoesCode/COM619DevOpsGroupWork#3]
Josh is leading this ticket with assistance from Ahub and Danny

**Comment by DAghaSolent** [comment]
Currently facing a blocker on this ticket which is not allowing deployment of this application to it's full effect.

Issues are there is no login section @AhubSajid Please check that you have pushed the right application or make changes so that we can have the login section.

@AhubSajid There is also another issue with post responses that are throwing up errors when trying to add a new POI this might be an issue with the routing since we have changed the routing to 8080. @AhubSajid @DAghaSolent @JoshC98 to look into this.

**Comment by GDoesCode** [comment]
@DAghaSolent and @JoshC98 can see the app on Azure.

**Comment by DAghaSolent** [comment]
@jacob-shattock-solent  can now see it on the outside
