### ISSUE TITLE
Set up SSL and create a site certificate so the app runs in HTTPS

### ISSUE THREAD

**Issue by DAghaSolent** [GDoesCode/COM619DevOpsGroupWork#7]

**Comment by GDoesCode** [comment]
@DAghaSolent @JoshC98 , can see the certificate and the SSL.

**Comment by DAghaSolent** [comment]
My automation testing has been able to open the web application and see the SSL certificate working in action.

@jacob-shattock-solent and @GDoesCode Once you have your Azures all configured can you see if you can access it and see the SSL certificates and then we can call this done

**Comment by DAghaSolent** [comment]
@jacob-shattock-solent can see it on the outside
